"""empty message

Revision ID: 476203eba4fd
Revises: 5dc287c19a96
Create Date: 2022-05-19 16:05:06.563503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476203eba4fd'
down_revision = '5dc287c19a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
